### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by GeorgeLEE85** [Tengfei-Wang/DCSR#1]
Hi guys,
Thanks for sharing this great work! I run your code and the SR results are quite appealing, and I really like this work. I have some questions and I am looking forward to your reply.
1. which device (smartphone) do u use to collect the Camerafusion dataset? Can this dataset be used for commercial usage?
2.  How long do u suggest training the model on CameraFusion? I trained the model for 1 day with one GPU (~15 epochs), and the SR results are already good enough. It seems that I do not need to continue the training until 1,000 epochs as in the default options.  

Thanks

**Comment by Tengfei-Wang** [comment]
Hi,
Thanks for your interest in our work.
1.  CameraFusion was collected by dual-cameras on iPhone11 Pro Max, and we are currently working on collecting a larger dataset with diverse devices. The proposed dataset is for research use only.
2.  You are right. The basic model takes about 1 day (10 ~ 20 epochs) for convergence, and you do not need to train it for 1000 epochs. The released basic model was trained with 12 epochs, and the SRA model was trained with 3 epochs.
