### ISSUE TITLE
question on dcsr.py

### ISSUE THREAD

**Issue by Lkinyuu** [Tengfei-Wang/DCSR#11]
with torch.no_grad():
          if coarse:

            B = lr.shape[0]
            ref_ = F.interpolate(ref, scale_factor=1/16, mode='bicubic')
            lr_ = F.interpolate(lr, scale_factor=1/8, mode='bicubic')
    
            i , P, r= self.select(lr_, ref_)
            
            for j in range(B):
              ref_p = ref[:, :,np.maximum((2*8*(i[j]//P)).cpu(),0):np.minimum((2*8*(i[j]//P)+2*lr.shape[2]).cpu(), ref.shape[2]), np.maximum((2*8*(i[j]%P)).cpu(),0):np.minimum((2*8*(i[j]%P)+2*lr.shape[3]).cpu(), ref.shape[3])]

          else: 
            ref_p = ref

**Comment by Lkinyuu** [comment]
I am a beginner，what is the meaning of this part?

**Comment by Lkinyuu** [comment]
And when train with CUFED5 ,what‘s the size of input and ref

**Comment by Tengfei-Wang** [comment]
1. this is a coarse-to-fine search scheme, which is designed for efficient reference patch searching.
2. The LR patch size is 40 and Ref patch size is 160. and you can modify it in the option.py.

**Comment by Lkinyuu** [comment]
thanks, another question is         if self.flag_8k:
            self.aa1 = AlignedAttention(scale=4, align=True) #swap4
            self.aa2 = AlignedAttention(scale=2, align = False) #swap3
            self.aa3 = AlignedAttention(scale=4, align=True) #swap2
        else:
            self.aa1 = AlignedAttention(scale=2, align=True) #swap4
            self.aa2 = AlignedAttention(scale=1, align = False) #swap3
            self.aa3 = AlignedAttention(scale=2, align=True) #swap2

**Comment by Lkinyuu** [comment]
the parameter of AlignedAttention. When 4k super-resolution, the scale=2 will lead to the results that only 2k
