### ISSUE TITLE
Question on patch_size

### ISSUE THREAD

**Issue by Brightlcz** [Tengfei-Wang/DCSR#12]
Hi, Thanks for sharing this excellent work! 
I have two questions.
1. I am debugging the released code and finding the shape of the I Ref patch and I LR patch is different.  The height and width of the I Ref patch are twice of the I LR patch. The extract reference features from I Ref is also different. Is this done for 2X SR?  
2. The input and output through the network are patch size. The whole picture is not fed into the network. How to achieve the SR of the whole picture?

Thanks

**Comment by Tengfei-Wang** [comment]
Hi,
1. Yes, it is for 2X SR.
2. When you run the `test.sh`, it will super-resolve all patches and then stitch these patches into a full image.
