### ISSUE TITLE
About  4x start

### ISSUE THREAD

**Issue by Lkinyuu** [Tengfei-Wang/DCSR#13]
I try to modify the network for 4x，but I am not capable.Error message prompt：index 【】is out of bounds for dimension 2 with size 【】. I don't know how to produce the correct result

**Comment by Lkinyuu** [comment]
For example, I set the scale of self.aa1() and FeatureMatching to 4 ,but failed

**Comment by Tengfei-Wang** [comment]
Hi,
For 4x SR, the scale of ref image is 4x of that of LR images. So we also need to modify the feature extractor (pretrained vgg) accordingly.  The key is to make sure the feature map sizes of  Ref and LR are the same so that we can calculate patch-wise cosine similarity. For example, we  modified 7 to 11 in this line:
https://github.com/Tengfei-Wang/DCSR/blob/70ff9069c350dc0afb845634bf5b424564ffe565/model/attention.py#L26 
And other lines specified on 2x SR should also be modified, like shape_out*4.  It can be a little tedious.
https://github.com/Tengfei-Wang/DCSR/blob/70ff9069c350dc0afb845634bf5b424564ffe565/model/attention.py#L110

**Comment by Lkinyuu** [comment]
> 嗨， 对于 4x SR，参考图像的比例是 LR 图像的 4 倍。所以我们还需要相应地修改特征提取器（预训练的 vgg）。关键是要确保 Ref 和 LR 的特征图大小相同，以便我们可以计算 patch-wise 余弦相似度。例如，我们将这一行中的 7 修改为 11：
> 
> https://github.com/Tengfei-Wang/DCSR/blob/70ff9069c350dc0afb845634bf5b424564ffe565/model/attention.py#L26
> 
> 
> 2x SR 上指定的其他行也应修改，如 shape_out*4。这可能有点乏味。
> https://github.com/Tengfei-Wang/DCSR/blob/70ff9069c350dc0afb845634bf5b424564ffe565/model/attention.py#L110

Maybe you mean         " for x in range(10):"? Because when modified 7 to 11 ，it will cause channels error .Besides,   if I follow the above method to modify parameters,  can I train on the CUFED5x4 to get the same results as in the paper?

**Comment by Lkinyuu** [comment]
> Hi, For 4x SR, the scale of ref image is 4x of that of LR images. So we also need to modify the feature extractor (pretrained vgg) accordingly. The key is to make sure the feature map sizes of Ref and LR are the same so that we can calculate patch-wise cosine similarity. For example, we modified 7 to 11 in this line:
> 
> https://github.com/Tengfei-Wang/DCSR/blob/70ff9069c350dc0afb845634bf5b424564ffe565/model/attention.py#L26
> 
> 
> And other lines specified on 2x SR should also be modified, like shape_out*4. It can be a little tedious.
> https://github.com/Tengfei-Wang/DCSR/blob/70ff9069c350dc0afb845634bf5b424564ffe565/model/attention.py#L110

Maybe you mean         " for x in range(10):"? Because when modified 7 to 11 ，it will cause channels error .Besides,   if I follow the above method to modify parameters,  can I train on the CUFED5x4 to get the same results as in the paper?

**Comment by Lkinyuu** [comment]
> Hi, For 4x SR, the scale of ref image is 4x of that of LR images. So we also need to modify the feature extractor (pretrained vgg) accordingly. The key is to make sure the feature map sizes of Ref and LR are the same so that we can calculate patch-wise cosine similarity. For example, we modified 7 to 11 in this line:
> 
> https://github.com/Tengfei-Wang/DCSR/blob/70ff9069c350dc0afb845634bf5b424564ffe565/model/attention.py#L26
> 
> 
> And other lines specified on 2x SR should also be modified, like shape_out*4. It can be a little tedious.
> https://github.com/Tengfei-Wang/DCSR/blob/70ff9069c350dc0afb845634bf5b424564ffe565/model/attention.py#L110
May I ask for the settings that train on the CUFED5 ? I want to reproduce the same result as in the paper.

**Comment by Lkinyuu** [comment]
@Tengfei-Wang
