### ISSUE TITLE
Sorry I'm asking stupid questions again

### ISSUE THREAD

**Issue by Lkinyuu** [Tengfei-Wang/DCSR#17]
Did I need modify the code in dataset? I guess this part of the code only applies to CameraFusion. I long to know the difference in dataset.py between DCSR (CUFED5) and other Refsr method .Because I originally wanted to directly apply the dataset code of other methods, but failed. @jiaxinxie97 @Tengfei-Wang

**Comment by Lkinyuu** [comment]
When I try to evaluate the trained model, the sr_list in __init__.py is empty. I don't know what caused it

**Comment by Tengfei-Wang** [comment]
Hi,
1. Yes, you need to modify the dataset code for other datasets. The key differences are the scale (2x or 4x or something else) and patch_select(). For CUFED5, you may refer to SRNTT or TTSR for dataset codes.
2. Could you show the reported errors? I guess the tested images are not placed well in your given directory.

**Comment by Lkinyuu** [comment]
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    main()
  File "main.py", line 26, in main
    trainer.evaluate()
  File "/content/drive/MyDrive/DCSR-master/trainer.py", line 160, in evaluate
    sr=self.model(LR_pad,Ref)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/DCSR-master/model/__init__.py", line 98, in forward
    sr_list = torch.cat(sr_list, dim=0)
NotImplementedError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors, or that you (the operator writer) forgot to register a fallback function.  Available functions are [CPU, CUDA, QuantizedCPU, BackendSelect, Python, Named, Conjugate, Negative, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradLazy, AutogradXPU, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, UNKNOWN_TENSOR_TYPE_ID, Autocast, Batched, VmapMode].                                     @Tengfei-Wang
