### ISSUE TITLE
About patch_select

### ISSUE THREAD

**Issue by Brightlcz** [Tengfei-Wang/DCSR#18]
Hi, @Tengfei-Wang 

First of all, I want to say thank you and ask you again.

Because the released codes are only training the overlapped FoV on CameraFusion.

So when training on CUFED5, I changed [L_x](https://github.com/Tengfei-Wang/DCSR/blob/70ff9069c350dc0afb845634bf5b424564ffe565/dataloader/common.py#L13) to L_x = random.randrange(0, L_w - L_p + 1 - 15) for training the whole image. 

When testing, I directly use the same corresponding position between the reference image and input image as a patch_ref because I think input image and reference image are very similar.  

So in the second for loop, I remove those [lines](https://github.com/Tengfei-Wang/DCSR/blob/70ff9069c350dc0afb845634bf5b424564ffe565/model/__init__.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L64-L86) and select the pixel value of patch_ref[] to  4x patch_LR in the same corresponding position and set course as False.

But the result is not good, I feel my choice of patch_ref is too simple, how can I do to achieve the result in the paper when training CUFED5?

Looking forward to your reply!

**Comment by Tengfei-Wang** [comment]
Hi,
For  CUFED5, we use the full ref image for inference (instead of a patch).

**Comment by Brightlcz** [comment]
Hi, @Tengfei-Wang 

Did you mean to use the full ref image only during the testing and use patch during the training ?

 Thanks in advance!
