### ISSUE TITLE
customized dataset

### ISSUE THREAD

**Issue by Junhe10** [Tengfei-Wang/DCSR#2]
Hi,
Thanks for sharing your code and the excellent ideas. 
I am doing a large-factor RefSR project (8x or 16x SR), and I found your results on CUFED5 and your proposed dataset are quite promising.  My question is how can  I modify the released code for my own datasets? Looking forward to your reply.
Cheers,
Junhe Zhang

**Comment by Tengfei-Wang** [comment]
Hi,
The released code is for 2X super-resolution on _CameraFusion_. In case you want to apply the code to 4x, 8x, and 16x SR, some modifications are needed (it should be easy though maybe tedious). For example, add additional layers in DCSR.py,  modify the data loader and turn off the option of _--flag_8k_.  If you want our 4x SR results on the CUFED5 test set, you can find them in [this link](https://hkustconnect-my.sharepoint.com/:f:/g/personal/tfwang_connect_ust_hk/EidZ5B1jPC9PmTlSUtrMbN0B4a2VY1hXrteYZevijllhJg?e=hQwva7). Feel free to let me know if you have any problems.

**Comment by Junhe10** [comment]
> Hi,
> The released code is for 2X super-resolution on _CameraFusion_. In case you want to apply the code to 4x, 8x, and 16x SR, some modifications are needed (it should be easy though maybe tedious). For example, add additional layers in DCSR.py, modify the data loader and turn off the option of _--flag_8k_. If you want our 4x SR results on the CUFED5 test set, you can find them in [this link](https://hkustconnect-my.sharepoint.com/:f:/g/personal/tfwang_connect_ust_hk/EidZ5B1jPC9PmTlSUtrMbN0B4a2VY1hXrteYZevijllhJg?e=hQwva7). Feel free to let me know if you have any problems.

Thanks for your suggestions.  I have successfully modified the 4x and 8x code and it works well on my own dataset.

**Comment by Brightlcz** [comment]
@jiaxinxie97 @Tengfei-Wang 
I am so sorry to bother you，I am quite a new student in SR field.😓
According to your tips,I still can't accomplish 4x SR  in my customized dataset, 
I konw that the released code is for 2X SR on CameraFusion and I want to train a 4x SR model on customized dataset.
could you please tell me where i should modificatons in the released code? 
I'll be satisfied if you can give me a hint.
Thank you in advance for your help sincerely!

**Comment by Lkinyuu** [comment]
> > Hi,
> > The released code is for 2X super-resolution on _CameraFusion_. In case you want to apply the code to 4x, 8x, and 16x SR, some modifications are needed (it should be easy though maybe tedious). For example, add additional layers in DCSR.py, modify the data loader and turn off the option of _--flag_8k_. If you want our 4x SR results on the CUFED5 test set, you can find them in [this link](https://hkustconnect-my.sharepoint.com/:f:/g/personal/tfwang_connect_ust_hk/EidZ5B1jPC9PmTlSUtrMbN0B4a2VY1hXrteYZevijllhJg?e=hQwva7). Feel free to let me know if you have any problems.
> 
> Thanks for your suggestions. I have successfully modified the 4x and 8x code and it works well on my own dataset.

Hello,I am a beginner in this field. Can I ask you how  modify the 4x ?

**Comment by Tengfei-Wang** [comment]
Hi @Brightlcz  @Lkinyuu,
Pls refer to #13.  Let me know if there are any difficulties.
