### ISSUE TITLE
Question on evaluation in the main paper

### ISSUE THREAD

**Issue by codeslake** [Tengfei-Wang/DCSR#5]
Hi, thanks for the intuitive work.
I am quite new to SR field, so please be patient with my questions ;)

For Table 1 in the main paper, is the model trained only with the CUFED5 dataset?
For Table 2 in the main paper, are the compared models also fine-tuned with the CameraFusion dataset?

Thanks, and congrats on the oral presentation in ICCV2021!

**Comment by Tengfei-Wang** [comment]
Hi, thanks for your interest in our work.
For table 1, all models are trained only on CUFED5.
For table 2, all models are trained only on CameraFusion.

**Comment by codeslake** [comment]
I see, thanks for the answer!
