### ISSUE TITLE
Question on alignment.py

### ISSUE THREAD

**Issue by codeslake** [Tengfei-Wang/DCSR#7]
Hi,

I have a question on [alignment.py](https://github.com/Tengfei-Wang/DCSR/blob/master/model/alignment.py) in which affine transformation is patch-wisely applied. I am not an expert on deformable convolution, which I believe the code is based on, so please be patient with my question ;)

1. In [`def _get_p_n(...)`](https://github.com/Tengfei-Wang/DCSR/blob/master/model/alignment.py#L99), why do you subtract 0.5 and add 0.6 to the range? Is it for the even-size kernel? 

2. In [`def _get_p(...)`](https://github.com/Tengfei-Wang/DCSR/blob/master/model/alignment.py#L153) Why do you add `(self.kernel_size-1)//2+0.5` to affined transformed coordinates? Shouldn't it be `(self.kernel_size-1)//2-0.5` for making coordinate range between 0~h-1?

**Comment by Tengfei-Wang** [comment]
It is for even-size kernels. Currently, the alignment only supports ever-sized kerkers. For example, when kernel size is 6,  this gives a local mesh grid of [-2.5, -1.5, -0.5, 0.5, 1.5, 2.5]^2.
In this case, add (self.kernel_size-1)//2+0.5=2.5 transform the local mesh grid to 0~5. We then add it on p_0 to obtain global mesh coordinates.

**Comment by codeslake** [comment]
> It is for even-size kernels. Currently, the alignment only supports ever-sized kerkers. For example, when kernel size is 6, this gives a local mesh grid of [-2.5, -1.5, -0.5, 0.5, 1.5, 2.5]^2. In this case, add (self.kernel_size-1)//2+0.5=2.5 transform the local mesh grid to 0~5. We then add it on p_0 to obtain global mesh coordinates.

But if you add `(self.kernel_size-1)//2+0.5`, the range of [global mesh coordinate](https://github.com/Tengfei-Wang/DCSR/blob/aa0a5e945e7285970632b41d3cce2167d9cce86a/model/alignment.py#L153) becomes 1\~h. It lies between 0\~h-1 if we add `(self.kernel_size-1)//2-0.5`. Isn't it the global mesh coordinate that should be in range 0\~h-1?

**Comment by Tengfei-Wang** [comment]
> > It is for even-size kernels. Currently, the alignment only supports ever-sized kerkers. For example, when kernel size is 6, this gives a local mesh grid of [-2.5, -1.5, -0.5, 0.5, 1.5, 2.5]^2. In this case, add (self.kernel_size-1)//2+0.5=2.5 transform the local mesh grid to 0~5. We then add it on p_0 to obtain global mesh coordinates.
> 
> But if you add `(self.kernel_size-1)//2+0.5`, the range of [global mesh coordinate](https://github.com/Tengfei-Wang/DCSR/blob/aa0a5e945e7285970632b41d3cce2167d9cce86a/model/alignment.py#L153) becomes 1~h. It lies between 0~h if we add `(self.kernel_size-1)//2-0.5`. Isn't it the global mesh coordinate that should be in range 0~h-1?

Yes, or you may also modify the range of p_0 to [0, h-1].

**Comment by codeslake** [comment]
Ok, Thanks for the answer!
