### ISSUE TITLE
Question on SRA Loss implementation

### ISSUE THREAD

**Issue by codeslake** [Tengfei-Wang/DCSR#8]
Hi,

In Eq 7 in the main paper, images in the L1 term are not applied with Gaussian. However, in [the code](https://github.com/Tengfei-Wang/DCSR/blob/aa0a5e945e7285970632b41d3cce2167d9cce86a/loss/__init__.py#L78-#L80) it seems like Gaussian is applied to images for the L1 loss no matter what. Is it intended? 

Thanks in advance!

**Comment by Tengfei-Wang** [comment]
It seems like a typo in the paper. For SRA, we used l1 loss with Gaussian blur as in the code.

**Comment by codeslake** [comment]
Thanks for the answer!
