### ISSUE TITLE
cannot reproduce 8k result as shown in the paper

### ISSUE THREAD

**Issue by Zeqiang-Lai** [Tengfei-Wang/DCSR#9]
I run the scripts provided in the repo, but cannot reproduce 8k result as shown in the paper. Besides, the color of patches of 8K SRA is inconsistent.

```
sh test_8k.sh
sh test_8k_SRA.sh
```

**result of test_8k**
![image](https://user-images.githubusercontent.com/26198430/136923592-5ac00756-c987-4f97-9b22-20bebe9b1c5e.png)

**result of test_8k_SRA**
![image](https://user-images.githubusercontent.com/26198430/136923553-a3547f4e-6dae-44e8-800e-474a33231735.png)

**results from the paper**
![image](https://user-images.githubusercontent.com/26198430/136923631-efc35dff-19c4-4708-bc7c-07ac4207d3ad.png)

![image](https://user-images.githubusercontent.com/26198430/136925123-388752f3-f266-4187-ac1f-cbd7a37b47fc.png)

**Comment by Tengfei-Wang** [comment]
1. As we modified some variable and class names in the code, the released model is a re-trained version, which may produce slightly different (but basically the same) results.  
2.  SRA may lead to some inconsistent colors outside the overlapped regions. We adopted post-processing to eliminate this discrepancy, but the post-processing scripts are not released. One alternative solution is to train the model only on the Y-Channel and add back the color channels directly.

**Comment by codeslake** [comment]
@Tengfei-Wang, It is actually an interesting answer. I am having trouble using contextual loss, which generates unexpected artifacts, the color discrepancy you are talking about. Do you mean YUV color space? but you still have to maintain RGB images for the VGG networks for the initial feature matching and the contextual loss, right? And is there any chance that you can share the post-processing scripts?

Best,

**Comment by Tengfei-Wang** [comment]
> @Tengfei-Wang, It is actually an interesting answer. I am having trouble using contextual loss, which generates unexpected artifacts, the color discrepancy you are talking about. Do you mean YUV color space? but you still have to maintain RGB images for the VGG networks for the initial feature matching and the contextual loss, right? And is there any chance that you can share the post-processing scripts?
> 
> Best,

I think the input images can still be RGB images for VGG feature extraction, and the output images can be gray ones. As this project is supported by the collaborated company, we do not have plans to release the post-processing scripts. But I suppose the YUV decomposition can be an alternative to the post-processing.

**Comment by codeslake** [comment]
> > @Tengfei-Wang, It is actually an interesting answer. I am having trouble using contextual loss, which generates unexpected artifacts, the color discrepancy you are talking about. Do you mean YUV color space? but you still have to maintain RGB images for the VGG networks for the initial feature matching and the contextual loss, right? And is there any chance that you can share the post-processing scripts?
> > Best,
> 
> I think the input images can still be RGB images for VGG feature extraction, and the output images can be gray ones. As this project is supported by the collaborated company, we do not have plans to release the post-processing scripts. But I suppose the YUV decomposition can be an alternative to the post-processing.

Hi, I understand about the script. Thanks for the answer though. 
About the YUV question, I was asking about your previous comment,

> SRA may lead to some inconsistent colors outside the overlapped regions. We adopted post-processing to eliminate this discrepancy, but the post-processing scripts are not released. One alternative solution is to train the model only on the Y-Channel and add back the color channels directly.

What is exactly the Y channel here? what I understood was, feeding the SR net with Y channel of an input encoded in YUV color space, while feeding the same input in RGB space for the module, in which feature matching is required (*e.g.*, vgg19 in the AA module and the contextual loss). Lastly, after the SR net produces an output in Y channel, we produce the final output by concatenating an upsampled UV channel of the input. I am not sure if I understood this right.  I am new in SR field, so I really wonder how SR people deal with this perceptual artifact :) Would please be more specific?

Thanks in advance!

**Comment by Tengfei-Wang** [comment]
> hile feeding

Hi,
I think the input image of the network can still be RGB image, but the output of the network can be modified to a single-channel image.  And then, the upsampled UV channels can be concatenated. Actually, many SR works adopt a similar strategy, as human eyes are more sensitive to the structure instead of colors.
